# A Campaign with global settings
[desktop]
campaign_tracking = "23-ba-171128"
preview_link = "/wiki/Wikipedia:Hauptseite?banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

# Banners of the campaign, key after "banners" can be anything
[desktop.banners.ctrl]
filename = "./desktop/banner_ctrl.js"
pagename = "B17WMDE_23_171128_ctrl"
tracking = "org-23-171128-ctrl"

[desktop.banners.var]
filename = "./desktop/banner_var.js"
pagename = "B17WMDE_23_171128_var"
tracking = "org-23-171128-var"


# Mobile Campaign
[mobile]
campaign_tracking = "mob03-ba-171110"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

[mobile.banners.ctrl]
filename = "./mobile/banner_ctrl.js"
pagename = "B17WMDE_mob_03_171110_ctrl"
tracking = "org-mob03-171110-ctrl"

[mobile.banners.var]
filename = "./mobile/banner_var.js"
pagename = "B17WMDE_mob_03_171110_var"
tracking = "org-mob03-171110-var"


# iPad campaign
[pad]
campaign_tracking = "pad01-ba-171117"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

[pad.banners.ctrl]
filename = "./pad/banner_ctrl.js"
pagename = "B17WMDE_pad_01_171116_ctrl"
tracking = "org-pad01-171117-ctrl"

[pad.banners.pad]
filename = "./pad/banner_var.js"
pagename = "B17WMDE_pad_01_171116_var"
tracking = "org-pad01-171117-var"


# Wikipedia.de Campaign
[wikipediade]
campaign_tracking = "09-ba-171006"
preview_link = "/wikipedia.de?bannertest=Banner/B17WMDE_webpack_prototype&devbanner={{banner}}"

[wikipediade.banners.ctrl]
filename = "./wikipedia.de/banner_ctrl.js"
pagename = "FR2016_09_171007_ctrl"
tracking = "org-09-171006-ctrl"

[wikipediade.banners.var]
filename = "./wikipedia.de/banner_var.js"
pagename = "FR2016_09_171007_var"
tracking = "org-09-171006-var"


# English Campaign
[english]
campaign_tracking = "en01-ba-171114"
preview_link = "/wiki/Wikipedia:Hauptseite?banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

[english.banners.ctrl]
filename = "./english/banner_ctrl.js"
pagename = "B17WMDE_en01_171113_ctrl"
tracking = "org-en01-171114-ctrl"

[english.banners.var]
filename = "./english/banner_var.js"
pagename = "B17WMDE_en01_171113_var"
tracking = "org-en01-171114-var"


[enwiki-default]
campaign_tracking = "ca17-default"
preview_link = "/wiki/Wikipedia:Hauptseite?banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

[enwiki-default.banners.default]
filename = "./english/banner_ctrl.js"
pagename = "B17WMDE_enwiki_desktop_default"
tracking = "org-desktop-en-171121"
