# NOTE: The "pagename" value must start with an uppercase "B" and should be followed by the year (YY) and WMDE.
# Example: "B18WMDE_"
# See https://github.com/wmde/fundraising-infrastructure/wiki/How-to-manage-banners-on-de.wikipedia.org

# A Campaign with global settings
[desktop]
campaign_tracking = "04-ba-180817"
preview_link = "/wiki/Wikipedia:Hauptseite?banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"


# Banners of the campaign, key after "banners" can be anything
[desktop.banners.ctrl]
filename = "./desktop/banner_ctrl.js"
pagename = "B18WMDE_04_180817_ctrl"
tracking = "org-04-180817-ctrl"

[desktop.banners.var]
filename = "./desktop/banner_var.js"
pagename = "B18WMDE_04_180817_var"
tracking = "org-04-180817-var"

[dewiki-default]
campaign_tracking = "ca17-default"
preview_link = "/wiki/Wikipedia:Hauptseite?banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[dewiki-default.banners.default]
filename = "./desktop/banner_ctrl.js"
pagename = "B17WMDE_dewiki_desktop_default"
tracking = "org-desktop-de-171113"


# Mobile Campaign
[mobile]
campaign_tracking = "mob01-ba-180901"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[mobile.banners.ctrl]
filename = "./mobile/banner_ctrl.js"
pagename = "B18WMDE_mob01_180901_ctrl"
tracking = "org-mob01-180901-ctrl"

[mobile.banners.var]
filename = "./mobile/banner_var.js"
pagename = "B18WMDE_mob01_180901_var"
tracking = "org-mob01-180901-var"

# Default mobile campaign
[mobile-default]
campaign_tracking = "ca17-default"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[mobile-default.banners.default]
filename = "./mobile/banner_ctrl.js"
pagename = "B17WMDE_dewiki_mobile_default"
tracking = "org-mob-de-171121"


# iPad campaign
[pad]
campaign_tracking = "pad04-ba-171218"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[pad.banners.ctrl]
filename = "./pad/banner_ctrl.js"
pagename = "B17WMDE_pad_04_171218_ctrl"
tracking = "org-pad04-171218-ctrl"

[pad.banners.pad]
filename = "./pad/banner_var.js"
pagename = "B17WMDE_pad_04_171218_var"
tracking = "org-pad04-171218-var"

# Default ipad campaign
[pad-default]
campaign_tracking = "ca17-default"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[pad-default.banners.default]
filename = "./pad/banner_ctrl.js"
pagename = "B17WMDE_dewiki_ipad_default"
tracking = "org-pad-de-171121"


# Wikipedia.de Campaign
[wikipediade]
campaign_tracking = "wpde-04-171218"
preview_link = "/wikipedia.de?bannertest=Banner/B17WMDE_webpack_prototype_for_raw_mode&devbanner={{banner}}"
wrapper_template = "wikipedia_de"

[wikipediade.banners.fulltop-ctrl]
filename = "./wikipedia.de/banner_fulltop_ctrl.js"
pagename = "B17WPDE_04_171218_fulltop_ctrl"
tracking = "wpde-04-171218-fulltop-ctrl"

[wikipediade.banners.top-ctrl]
filename = "./wikipedia.de/banner_top_ctrl.js"
pagename = "B17WPDE_04_171218_top_ctrl"
tracking = "wpde-04-171218-top-ctrl"

[wikipediade.banners.fulltop-var]
filename = "./wikipedia.de/banner_fulltop_var.js"
pagename = "B17WPDE_04_171218_fulltop_var"
tracking = "wpde-04-171218-fulltop-var"

[wikipediade.banners.top-var]
filename = "./wikipedia.de/banner_top_var.js"
pagename = "B17WPDE_04_171218_top_var"
tracking = "wpde-04-171218-top-var"


# English Campaign
[english]
campaign_tracking = "en03-ba-171218"
preview_link = "/wiki/Wikipedia:Hauptseite?banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[english.banners.ctrl]
filename = "./english/banner_ctrl.js"
pagename = "B17WMDE_en03_171218_ctrl"
tracking = "org-en03-171218-ctrl"

[english.banners.var]
filename = "./english/banner_var.js"
pagename = "B17WMDE_en03_171218_var"
tracking = "org-en03-171218-var"

[enwiki-default]
campaign_tracking = "ca17-default"
preview_link = "/wiki/Wikipedia:Hauptseite?banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[enwiki-default.banners.default]
filename = "./english/banner_ctrl.js"
pagename = "B17WMDE_enwiki_desktop_default"
tracking = "org-desktop-en-171121"


# Mobile Slider Campaign
[mobile_slider]
campaign_tracking = ""
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[mobile_slider.banners.ctrl]
filename = "./mobile_slider/banner_ctrl.js"
pagename = "B18WMDE_mob_prototype"
tracking = "org-mob06-180501-ctrl"