# A Campaign with global settings
[desktop]
campaign_tracking = "33-ba-171215"
preview_link = "/wiki/Wikipedia:Hauptseite?banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

# Banners of the campaign, key after "banners" can be anything
[desktop.banners.ctrl]
filename = "./desktop/banner_ctrl.js"
pagename = "B17WMDE_33_171215_ctrl"
tracking = "org-33-171215-ctrl"

[desktop.banners.var]
filename = "./desktop/banner_var.js"
pagename = "B17WMDE_33_171215_var"
tracking = "org-33-171215-var"

[dewiki-default]
campaign_tracking = "ca17-default"
preview_link = "/wiki/Wikipedia:Hauptseite?banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

[dewiki-default.banners.default]
filename = "./desktop/banner_ctrl.js"
pagename = "B17WMDE_dewiki_desktop_default"
tracking = "org-desktop-de-171113"


# Mobile Campaign
[mobile]
campaign_tracking = "mob04-ba-171127"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

[mobile.banners.ctrl]
filename = "./mobile/banner_ctrl.js"
pagename = "B17WMDE_mob_04_171127_ctrl"
tracking = "org-mob04-171127-ctrl"

[mobile.banners.var]
filename = "./mobile/banner_var.js"
pagename = "B17WMDE_mob_04_171127_var"
tracking = "org-mob04-171127-var"

# Default mobile campaign
[mobile-default]
campaign_tracking = "ca17-default"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

[mobile-default.banners.default]
filename = "./mobile/banner_ctrl.js"
pagename = "B17WMDE_dewiki_mobile_default"
tracking = "org-mob-de-171121"


# iPad campaign
[pad]
campaign_tracking = "pad03-ba-171205"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

[pad.banners.ctrl]
filename = "./pad/banner_ctrl.js"
pagename = "B17WMDE_pad_03_171205_ctrl"
tracking = "org-pad03-171205-ctrl"

[pad.banners.pad]
filename = "./pad/banner_var.js"
pagename = "B17WMDE_pad_03_171205_var"
tracking = "org-pad03-171205-var"

# Default ipad campaign
[pad-default]
campaign_tracking = "ca17-default"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

[pad-default.banners.default]
filename = "./pad/banner_ctrl.js"
pagename = "B17WMDE_dewiki_ipad_default"
tracking = "org-pad-de-171121"


# Wikipedia.de Campaign
[wikipediade]
campaign_tracking = "09-ba-171006"
preview_link = "/wikipedia.de?bannertest=Banner/B17WMDE_webpack_prototype&devbanner={{banner}}"

[wikipediade.banners.ctrl]
filename = "./wikipedia.de/banner_ctrl.js"
pagename = "FR2016_09_171007_ctrl"
tracking = "org-09-171006-ctrl"

[wikipediade.banners.var]
filename = "./wikipedia.de/banner_var.js"
pagename = "FR2016_09_171007_var"
tracking = "org-09-171006-var"


# English Campaign
[english]
campaign_tracking = "en02-ba-171127"
preview_link = "/wiki/Wikipedia:Hauptseite?banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

[english.banners.ctrl]
filename = "./english/banner_ctrl.js"
pagename = "B17WMDE_en02_171127_ctrl"
tracking = "org-en02-171127-ctrl"

[english.banners.var]
filename = "./english/banner_var.js"
pagename = "B17WMDE_en02_171127_var"
tracking = "org-en02-171127-var"


[enwiki-default]
campaign_tracking = "ca17-default"
preview_link = "/wiki/Wikipedia:Hauptseite?banner=B17WMDE_webpack_prototype&devbanner={{banner}}"

[enwiki-default.banners.default]
filename = "./english/banner_ctrl.js"
pagename = "B17WMDE_enwiki_desktop_default"
tracking = "org-desktop-en-171121"
